function contentUI(){
	return  '<div id="service">'
    +'<section id="slider">'
        +'<div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel" data-interval="3000">'
            +'<!-- Indicators -->'
            +'<ol class="carousel-indicators">'
                +'<li data-target="#carousel-example-generic" data-slide-to="0" class=""></li>'
                +'<li data-target="#carousel-example-generic" data-slide-to="1" class="active"></li>'
                +'<li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>'
            +'</ol>'
+''
            +'<!-- Wrapper for slides -->'
            +'<div class="carousel-inner" role="listbox">'
                +'<div class="item active left">'
                    +'<div class="slider_overlay">'
                        +'<img src="'+$.ctx()+'/resources/img/img1.jpg" alt="...">'
                        +'<div class="carousel-caption">'
                            +'<div class="slider_text">'
                                +'<h3>Protect</h3>'
                                +'<h2>nature the environment</h2>'
                                +'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>'
                                +'<a href="" class="custom_btn">Read  More</a>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of item With Active-->'
                +'<div class="item next left">'
                    +'<div class="slider_overlay">'
                        +'<img src="'+$.ctx()+'/resources/img/img2.jpg" alt="...">'
                        +'<div class="carousel-caption">'
                            +'<div class="slider_text">'
                                +'<h3>Protect</h3>'
                                +'<h2>nature the environment</h2>'
                                +'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>'
                                +'<a href="" class="custom_btn">Read  More</a>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of Item-->'
                +'<div class="item">'
                    +'<div class="slider_overlay">'
                        +'<img src="'+$.ctx()+'/resources/img/img3.jpg" alt="...">'
                        +'<div class="carousel-caption">'
                            +'<div class="slider_text">'
                                +'<h3>Protect</h3>'
                                +'<h2>nature the environment</h2>'
                                +'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>'
                                +'<a href="" class="custom_btn">Read  More</a>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of item-->'
            +'</div>'
            +'<!--End of Carousel Inner-->'
        +'</div>'
    +'</section>'
    +'<!--end of slider section-->'
+''
+''
+''
    +'<!--Start of welcome section-->'
    +'<section id="welcome">'
        +'<div class="container">'
            +'<div class="row">'
                +'<div class="col-md-12">'
                    +'<div class="wel_header">'
                        +'<h2>welcome to green fair</h2>'
                        +'<p>Our Green Fire Organization is one of the non profit organization near you. Get our services like</p>'
                    +'</div>'
                +'</div>'
            +'</div>'
            +'<!--End of row-->'
            +'<div class="row">'
                +'<div class="col-md-3">'
                    +'<div class="item">'
                        +'<div class="single_item">'
                            +'<div class="item_list">'
                                +'<div class="welcome_icon">'
                                    +'<i class="fa fa-leaf"></i>'
                                +'</div>'
                                +'<h4>eco system</h4>'
                                +'<p>Lorem ipsum dolor sit amet, eu qui modo expetendis reformidans ex sit set appetere sententiae seo eum in simul homero.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-3-->'
                +'<div class="col-md-3">'
                    +'<div class="item">'
                        +'<div class="single_item">'
                            +'<div class="item_list">'
                                +'<div class="welcome_icon">'
                                    +'<i class="fa fa-refresh"></i>'
                                +'</div>'
                                +'<h4>recycling</h4>'
                                +'<p>Lorem ipsum dolor sit amet, eu qui modo expetendis reformidans ex sit set appetere sententiae seo eum in simul homero.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-3-->'
                +'<div class="col-md-3">'
                    +'<div class="item">'
                        +'<div class="single_item">'
                            +'<div class="item_list">'
                                +'<div class="welcome_icon">'
                                    +'<i class="fa fa-tint"></i>'
                                +'</div>'
                                +'<h4>water refine</h4>'
                                +'<p>Lorem ipsum dolor sit amet, eu qui modo expetendis reformidans ex sit set appetere sententiae seo eum in simul homero.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-3-->'
                +'<div class="col-md-3">'
                    +'<div class="item">'
                        +'<div class="single_item">'
                            +'<div class="item_list">'
                                +'<div class="welcome_icon">'
                                    +'<i class="fa fa-cog"></i>'
                                +'</div>'
                                +'<h4>solar system</h4>'
                                +'<p>Lorem ipsum dolor sit amet, eu qui modo expetendis reformidans ex sit set appetere sententiae seo eum in simul homero.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-3-->'
            +'</div>'
            +'<!--End of row-->'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!--end of welcome section-->'
+''
+''
+''
    +'<!--Start of volunteer-->'
    +'<section id="volunteer">'
        +'<div class="container">'
            +'<div class="row vol_area">'
                +'<div class="col-md-8">'
                    +'<div class="volunteer_content">'
                        +'<h3>Become a <span>Volunteer</span></h3>'
                        +'<p>Join Our Team And Help the world. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur.</p>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-8-->'
                +'<div class="col-md-3 col-md-offset-1">'
                    +'<div class="join_us">'
                        +'<a href="" class="vol_cust_btn">join us</a>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-3-->'
            +'</div>'
            +'<!--End of row and vol_area-->'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!--end of volunteer-->'
+''
+''
+''
    +'<!--Start of portfolio-->'
    +'<section id="portfolio" class="text-center">'
        +'<div class="col-md-12">'
            +'<div class="portfolio_title">'
                +'<h2>our latest work</h2>'
                +'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet consectetur adipiscing elit.</p>'
            +'</div>'
        +'</div>'
        +'<!--End of col-md-2-->'
        +'<div class="colum">'
            +'<div class="container">'
                +'<div class="row">'
                    +'<form action="/">'
                        +'<ul id="portfolio_menu" class="menu portfolio_custom_menu">'
                            +'<li>'
                                +'<button data-filter="*" class="my_btn btn_active">Show All</button>'
                            +'</li>'
                            +'<li>'
                                +'<button data-filter=".blue, .black, .green" class="my_btn">environment</button>'
                            +'</li>'
                            +'<li>'
                                +'<button data-filter=".red, .green" class="my_btn">climate</button>'
                            +'</li>'
                            +'<li>'
                                +'<button data-filter=".blue, .yellow, .black" class="my_btn">photography</button>'
                            +'</li>'
                            +'<li>'
                                +'<button data-filter=".black" class="my_btn">species</button>'
                                +'<!--'
                            +'</li>'
                            +'<li>'
                                +'<button data-filter=".black" class="my_btn">Black</button>'
                            +'</li>'
                                +'-->'
                        +'</li></ul>'
                        +'<!--End of portfolio_menu-->'
                    +'</form>'
                    +'<!--End of Form-->'
                +'</div>'
                +'<!--End of row-->'
            +'</div>'
            +'<!--End of container-->'
            +'<div class="container">'
                +'<div class="row">'
                    +'<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">'
                        +'<div class="notes" style="position: relative; height: 410px;">'
                            +'<div class="note blue" style="position: absolute; left: 0px; top: 0px;">'
                                +'<div class="img_overlay">'
                                    +'<p>Sun Homes, Dhaka</p>'
                                +'</div>'
                                +'<img src="'+$.ctx()+'/resources/img/environment.jpg" alt="">'
                            +'</div>'
                            +'<div class="note red" style="position: absolute; left: 381px; top: 0px;">'
                                +'<div class="img_overlay">'
                                    +'<p>Sun Homes, Dhaka</p>'
                                +'</div>'
                                +'<img src="'+$.ctx()+'/resources/img/portfolio_1.jpg" alt="">'
                            +'</div>'
                            +'<div class="note green" style="position: absolute; left: 0px; top: 205px;">'
                                +'<div class="img_overlay">'
                                    +'<p>Sun Homes, Dhaka</p>'
                                +'</div>'
                                +'<img src="'+$.ctx()+'/resources/img/cliemate.jpg" alt="">'
                            +'</div>'
                            +'<div class="note yellow" style="position: absolute; left: 668px; top: 0px;">'
                                +'<div class="img_overlay">'
                                    +'<p>Sun Homes, Dhaka</p>'
                                +'</div>'
                                +'<img src="'+$.ctx()+'/resources/img/photography.jpg" alt="">'
                            +'</div>'
                            +'<div class="note black" style="position: absolute; left: 287px; top: 205px;">'
                                +'<div class="img_overlay">'
                                    +'<p>Sun Homes, Dhaka</p>'
                                +'</div>'
                                +'<img src="'+$.ctx()+'/resources/img/species.jpg" alt="">'
                            +'</div>'
                        +'</div>'
                        +'<!--End of notes-->'
                    +'</div>'
                    +'<!--End of col-lg-12-->'
                +'</div>'
                +'<!--End of row-->'
            +'</div>'
            +'<!--End of container-->'
        +'</div>'
        +'<!--End of colum-->'
    +'</section>'
    +'<!--end of portfolio-->'
+''
+''
+''

+''
+''
+''
    +'<!--start of event-->'
    +'<section id="event">'
        +'<div class="container">'
            +'<div class="row">'
                +'<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">'
                    +'<div class="event_header text-center">'
                        +'<h2>latest event</h2>'
                        +'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>'
                    +'</div>'
                +'</div>'
            +'</div>'
            +'<!--End of row-->'
            +'<div class="row">'
                +'<div class="col-md-8">'
                    +'<div class="row">'
                        +'<div class="col-md-6 zero_mp">'
                            +'<div class="event_item">'
                                +'<div class="event_img">'
                                    +'<img src="'+$.ctx()+'/resources/img/tree_cut_1.jpg" alt="">'
                                +'</div>'
                            +'</div>'
                        +'</div>'
                        +'<div class="col-md-6 zero_mp">'
                            +'<div class="event_item">'
                                +'<div class="event_text text-center">'
                                    +'<a href=""><h4>One Tree Thousand Hope</h4></a>'
                                    +'<h6>15-16 May in Dhaka</h6>'
                                    +'<p>Lorem ipsum dolor sit amet, consectetur adip scing elit. Lorem ipsum dolor sit amet,consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>'
                                    +'<a href="" class="event_btn">read more</a>'
                                +'</div>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                    +'<!--End of row-->'
                    +'<div class="row">'
                        +'<div class="col-md-6 zero_mp">'
                            +'<div class="event_item">'
                                +'<div class="event_text text-center">'
                                    +'<a href=""><h4>One Tree Thousand Hope</h4></a>'
                                    +'<h6>15-16 May in Dhaka</h6>'
                                    +'<p>Lorem ipsum dolor sit amet, consectetur adip scing elit. Lorem ipsum dolor sit amet,consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>'
                                    +'<a href="" class="event_btn">read more</a>'
                                +'</div>'
                            +'</div>'
                        +'</div>'
                        +'<div class="col-md-6 zero_mp">'
                            +'<div class="event_item">'
                                +'<div class="event_img">'
                                    +'<img src="'+$.ctx()+'/resources/img/tree_cut_2.jpg" alt="">'
                                +'</div>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                    +'<!--End of row-->'
                +'</div>'
                +'<!--End of col-md-8-->'
                +'<div class="col-md-4">'
                    +'<div class="event_news">'
                        +'<div class="event_single_item fix">'
                            +'<div class="event_news_img floatleft">'
                                +'<img src="'+$.ctx()+'/resources/img/tree_cut_3.jpg" alt="">'
                            +'</div>'
                            +'<div class="event_news_text">'
                                +'<a href="#"><h4>Let’s plant 200 tree each...</h4></a>'
                                +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, veniam.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                    +'<div class="event_news">'
                        +'<div class="event_single_item fix">'
                            +'<div class="event_news_img floatleft">'
                                +'<img src="'+$.ctx()+'/resources/img/tree_cut_4.jpg" alt="">'
                            +'</div>'
                            +'<div class="event_news_text">'
                                +'<a href="#"><h4>Keep your house envirome..</h4></a>'
                                +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, veniam.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                    +'<div class="event_news">'
                        +'<div class="event_single_item fix">'
                            +'<div class="event_news_img floatleft">'
                                +'<img src="'+$.ctx()+'/resources/img/tree_cut_3.jpg" alt="">'
                            +'</div>'
                            +'<div class="event_news_text">'
                                +'<a href="#"><h4>Urgent Clothe Needed Needed</h4></a>'
                                +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, veniam.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                    +'<div class="event_news">'
                        +'<div class="event_single_item fix">'
                            +'<div class="event_news_img floatleft">'
                                +'<img src="'+$.ctx()+'/resources/img/tree_cut_4.jpg" alt="">'
                            +'</div>'
                            +'<div class="event_news_text">'
                                +'<a href="#"><h4>One Tree Thousand Hope</h4></a>'
                                +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, veniam.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                    +'<div class="event_news">'
                        +'<div class="event_single_item fix">'
                            +'<div class="event_news_img floatleft">'
                                +'<img src="'+$.ctx()+'/resources/img/tree_cut_3.jpg" alt="">'
                            +'</div>'
                            +'<div class="event_news_text">'
                                +'<a href="#"><h4>One Tree Thousand Hope</h4></a>'
                                +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid, veniam.</p>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-4-->'
            +'</div>'
            +'<!--End of row-->'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!--end of event-->'
+''
+''
+''
    +'<!--Start of testimonial-->'
    +'<section id="testimonial">'
        +'<div class="testimonial_overlay">'
            +'<div class="container">'
                +'<div class="row">'
                    +'<div class="col-md-12">'
                        +'<div class="testimonial_header text-center">'
                            +'<h2>testimonials</h2>'
                            +'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of row-->'
                +'<section id="carousel">'
                    +'<div class="container">'
                        +'<div class="row">'
                            +'<div class="col-md-12 text-center">'
                                +'<div class="carousel slide" id="fade-quote-carousel" data-ride="carousel" data-interval="3000">'
                                    +'<!-- Carousel indicators -->'
                                    +'<ol class="carousel-indicators">'
                                        +'<li data-target="#fade-quote-carousel" data-slide-to="0" class=""></li>'
                                        +'<li data-target="#fade-quote-carousel" data-slide-to="1" class="active"></li>'
                                    +'</ol>'
                                    +'<!-- Carousel items -->'
                                    +'<div class="carousel-inner">'
                                        +'<div class="item">'
                                            +'<div class="row">'
                                                +'<div class="col-md-6">'
                                                    +'<div class="profile-circle">'
                                                        +'<img src="'+$.ctx()+'/resources/img/tree_cut_3.jpg" alt="">'
                                                    +'</div>'
                                                    +'<div class="testimonial_content">'
                                                        +'<i class="fa fa-quote-left"></i>'
                                                        +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, veritatis nulla eum laudantium totam tempore optio doloremque laboriosam quas, quos eaque molestias odio aut eius animi. Impedit temporibus nisi accusamus.</p>'
                                                    +'</div>'
                                                    +'<div class="testimonial_author">'
                                                        +'<h5>Sadequr Rahman Sojib</h5>'
                                                        +'<p>CEO, Fourder</p>'
                                                    +'</div>'
                                                +'</div>'
                                                +'<div class="col-md-6">'
                                                    +'<div class="profile-circle">'
                                                        +'<img src="'+$.ctx()+'/resources/img/tree_cut_3.jpg" alt="">'
                                                    +'</div>'
                                                    +'<div class="testimonial_content">'
                                                        +'<i class="fa fa-quote-left"></i>'
                                                        +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, veritatis nulla eum laudantium totam tempore optio doloremque laboriosam quas, quos eaque molestias odio aut eius animi. Impedit temporibus nisi accusamus.</p>'
                                                    +'</div>'
                                                    +'<div class="testimonial_author">'
                                                        +'<h5>Sadequr Rahman Sojib</h5>'
                                                        +'<p>CEO, Fourder</p>'
                                                    +'</div>'
                                                +'</div>'
                                            +'</div>'
                                        +'</div>'
                                        +'<!--End of item with active-->'
                                        +'<div class="item active">'
                                            +'<div class="row">'
                                                +'<div class="col-md-6">'
                                                    +'<div class="profile-circle">'
                                                        +'<img src="'+$.ctx()+'/resources/img/tree_cut_3.jpg" alt="">'
                                                    +'</div>'
                                                    +'<div class="testimonial_content">'
                                                        +'<i class="fa fa-quote-left"></i>'
                                                        +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, veritatis nulla eum laudantium totam tempore optio doloremque laboriosam quas, quos eaque molestias odio aut eius animi. Impedit temporibus nisi accusamus.</p>'
                                                    +'</div>'
                                                    +'<div class="testimonial_author">'
                                                        +'<h5>Sadequr Rahman Sojib</h5>'
                                                        +'<p>CEO, Fourder</p>'
                                                    +'</div>'
                                                +'</div>'
                                                +'<div class="col-md-6">'
                                                    +'<div class="profile-circle">'
                                                        +'<img src="'+$.ctx()+'/resources/img/tree_cut_3.jpg" alt="">'
                                                    +'</div>'
                                                    +'<div class="testimonial_content">'
                                                        +'<i class="fa fa-quote-left"></i>'
                                                        +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, veritatis nulla eum laudantium totam tempore optio doloremque laboriosam quas, quos eaque molestias odio aut eius animi. Impedit temporibus nisi accusamus.</p>'
                                                    +'</div>'
                                                    +'<div class="testimonial_author">'
                                                        +'<h5>Sadequr Rahman Sojib</h5>'
                                                        +'<p>CEO, Fourder</p>'
                                                    +'</div>'
                                                +'</div>'
                                            +'</div>'
                                        +'</div>'
                                        +'<!--ENd of item-->'
                                    +'</div>'
                                +'</div>'
                            +'</div>'
                        +'</div>'
                        +'<!--End of row-->'
                    +'</div>'
                    +'<!--End of container-->'
                +'</section>'
                +'<!--End of carousel-->'
            +'</div>'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!--end of testimonial-->'
+''
+''
+''
    +'<!--Start of blog-->'
    +'<section id="blog">'
        +'<div class="container">'
            +'<div class="row">'
                +'<div class="col-md-12">'
                    +'<div class="latest_blog text-center">'
                        +'<h2>latest blog</h2>'
                        +'<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo cum libero vitae quos eaque commodi.</p>'
                    +'</div>'
                +'</div>'
            +'</div>'
            +'<!--End of row-->'
            +'<div class="row">'
                +'<div class="col-md-4">'
                    +'<div class="blog_news">'
                        +'<div class="single_blog_item">'
                            +'<div class="blog_img">'
                                +'<img src="'+$.ctx()+'/resources/img/climate_effect.jpg" alt="">'
                            +'</div>'
                            +'<div class="blog_content">'
                                +'<a href=""><h3>Climate change is affecting bird migration</h3></a>'
                                +'<div class="expert">'
                                    +'<div class="left-side text-left">'
                                        +'<p class="left_side">'
                                            +'<span class="clock"><i class="fa fa-clock-o"></i></span>'
                                            +'<span class="time">Aug 19, 2016</span>'
                                            +'<a href=""><span class="admin"><i class="fa fa-user"></i> Admin</span></a>'
                                        +'</p>'
                                        +'<p class="right_side text-right">'
                                            +'<a href=""><span class="right_msg text-right"><i class="fa fa-comments-o"></i></span>'
                                                +'<span class="count">0</span></a>'
                                        +'</p>'
                                    +'</div>'
                                +'</div>'
+''
                                +'<p class="blog_news_content">Lorem ipsum dolor sit amet, consectetur adipscing elit. Lorem ipsum dolor sit amet, conse ctetur adipiscing elit. consectetur Lorem ipsum dolor sitamet, conse ctetur adipiscing elit. </p>'
                                +'<a href="" class="blog_link">read more</a>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-4-->'
                +'<div class="col-md-4">'
                    +'<div class="blog_news">'
                        +'<div class="single_blog_item">'
                            +'<div class="blog_img">'
                                +'<img src="'+$.ctx()+'/resources/img/air_pollutuon.jpg" alt="">'
                            +'</div>'
                            +'<div class="blog_content">'
                                +'<a href=""><h3>How to avoid indoor air pollution?</h3></a>'
                                +'<div class="expert">'
                                    +'<div class="left-side text-left">'
                                        +'<p class="left_side">'
                                            +'<span class="clock"><i class="fa fa-clock-o"></i></span>'
                                            +'<span class="time">Aug 19, 2016</span>'
                                            +'<a href=""><span class="admin"><i class="fa fa-user"></i> Admin</span></a>'
                                        +'</p>'
                                        +'<p class="right_side text-right">'
                                            +'<a href=""><span class="right_msg text-right"><i class="fa fa-comments-o"></i></span>'
                                                +'<span class="count">0</span></a>'
                                        +'</p>'
                                    +'</div>'
                                +'</div>'
+''
                                +'<p class="blog_news_content">Lorem ipsum dolor sit amet, consectetur adipscing elit. Lorem ipsum dolor sit amet, conse ctetur adipiscing elit. consectetur Lorem ipsum dolor sitamet, conse ctetur adipiscing elit. </p>'
                                +'<a href="" class="blog_link">read more</a>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-4-->'
                +'<div class="col-md-4">'
                    +'<div class="blog_news">'
                        +'<div class="single_blog_item">'
                            +'<div class="blog_img">'
                                +'<img src="'+$.ctx()+'/resources/img/threat_bear.jpg" alt="">'
                            +'</div>'
                            +'<div class="blog_content">'
                                +'<a href=""><h3>Threat to Yellowstone’s grizzly bears.</h3></a>'
                                +'<div class="expert">'
                                    +'<div class="left-side text-left">'
                                        +'<p class="left_side">'
                                            +'<span class="clock"><i class="fa fa-clock-o"></i></span>'
                                            +'<span class="time">Aug 19, 2016</span>'
                                            +'<a href=""><span class="admin"><i class="fa fa-user"></i> Admin</span></a>'
                                        +'</p>'
                                        +'<p class="right_side text-right">'
                                            +'<a href=""><span class="right_msg text-right"><i class="fa fa-comments-o"></i></span>'
                                                +'<span class="count">0</span></a>'
                                        +'</p>'
                                    +'</div>'
                                +'</div>'
+''
                                +'<p class="blog_news_content">Lorem ipsum dolor sit amet, consectetur adipscing elit. Lorem ipsum dolor sit amet, conse ctetur adipiscing elit. consectetur Lorem ipsum dolor sitamet, conse ctetur adipiscing elit. </p>'
                                +'<a href="" class="blog_link">read more</a>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-4-->'
            +'</div>'
            +'<!--End of row-->'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!-- end of blog-->'
+''
+''
+''
    +'<!--Start of Purches-->'
    +'<section id="purches">'
        +'<div class="container">'
            +'<div class="row">'
                +'<div class="col-md-6">'
                    +'<h2 class="purches_title">Buy our wordpress theme</h2>'
                +'</div>'
                +'<div class="col-md-2 col-md-offset-4">'
                    +'<a href="" class="purches_btn">purches</a>'
                +'</div>'
            +'</div>'
            +'<!--End of row-->'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!--End of purches-->'
+''
+''
+''
    +'<!--Start of Market-->'
    +'<section id="market">'
        +'<div class="container">'
            +'<div class="row">'
                +'<div class="col-md-12">'
                    +'<div class="market_area text-center">'
                        +'<div class="row">'
                            +'<div class="col-md-3">'
                                +'<div class="market_logo">'
                                    +'<a href=""><img src="'+$.ctx()+'/resources/img/audiojungle.png" alt=""></a>'
                                +'</div>'
                            +'</div>'
                            +'<div class="col-md-3">'
                                +'<div class="market_logo">'
                                    +'<a href=""><img src="'+$.ctx()+'/resources/img/codecanyon.png" alt=""></a>'
                                +'</div>'
                            +'</div>'
                            +'<div class="col-md-3">'
                                +'<div class="market_logo">'
                                    +'<a href=""><img src="'+$.ctx()+'/resources/img/graphicriver.png" alt=""></a>'
                                +'</div>'
                            +'</div>'
                            +'<div class="col-md-3">'
                                +'<div class="market_logo">'
                                    +'<a href=""><img src="'+$.ctx()+'/resources/img/audiojungle.png" alt=""></a>'
                                +'</div>'
                            +'</div>'
                        +'</div>'
                        +'<!--End of row-->'
                    +'</div>'
                    +'<!--End of market Area-->'
                +'</div>'
                +'<!--End of col-md-12-->'
            +'</div>'
            +'<!--End of row-->'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!--End of market-->'
+''
+''
+''
    +'<!--Start of contact-->'
    +'<section id="contact">'
        +'<div class="container">'
            +'<div class="row">'
                +'<div class="colmd-12">'
                    +'<div class="contact_area text-center">'
                        +'<h3>get in touch</h3>'
                        +'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>'
                    +'</div>'
                +'</div>'
            +'</div>'
            +'<!--End of row-->'
            +'<div class="row">'
                +'<div class="col-md-6">'
                    +'<div class="office">'
                        +'<div class="title">'
                            +'<h5>our office info</h5>'
                        +'</div>'
                        +'<div class="office_location">'
                            +'<div class="address">'
                                +'<i class="fa fa-map-marker"><span>Elephant Road, Dhaka 1205, Bangladesh</span></i>'
                            +'</div>'
                            +'<div class="phone">'
                                +'<i class="fa fa-phone"><span>+ 8801532-987039</span></i>'
                            +'</div>'
                            +'<div class="email">'
                                +'<i class="fa fa-envelope"><span>youremail@mail.com</span></i>'
                            +'</div>'
                            //+'<div id="map" style="position: relative; overflow: hidden;"><div style="height: 100%; width: 100%; position: absolute; top: 0px; left: 0px; background-color: rgb(229, 227, 223);"><div class="gm-style" style="position: absolute; z-index: 0; left: 0px; top: 0px; height: 100%; width: 100%; padding: 0px; border-width: 0px; margin: 0px;"><div tabindex="0" style="position: absolute; z-index: 0; left: 0px; top: 0px; height: 100%; width: 100%; padding: 0px; border-width: 0px; margin: 0px; cursor: url(&quot;https://maps.gstatic.com/mapfiles/openhand_8_8.cur&quot;), default; touch-action: pan-x pan-y;"><div style="z-index: 1; position: absolute; left: 50%; top: 50%; width: 100%; transform: translate(0px, 0px);"><div style="position: absolute; left: 0px; top: 0px; z-index: 100; width: 100%;"><div style="position: absolute; left: 0px; top: 0px; z-index: 0;"><div style="position: absolute; z-index: 1; transform: matrix(1, 0, 0, 1, -138, -95);"><div style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: -256px; top: 0px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: -256px; top: -256px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: 0px; top: -256px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: 256px; top: -256px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: 256px; top: 0px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: -512px; top: 0px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: -512px; top: -256px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: 512px; top: -256px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div><div style="position: absolute; left: 512px; top: 0px; width: 256px; height: 256px;"><div style="width: 256px; height: 256px;"></div></div></div></div></div><div style="position: absolute; left: 0px; top: 0px; z-index: 101; width: 100%;"></div><div style="position: absolute; left: 0px; top: 0px; z-index: 102; width: 100%;"></div><div style="position: absolute; left: 0px; top: 0px; z-index: 103; width: 100%;"><div style="position: absolute; left: 0px; top: 0px; z-index: -1;"><div style="position: absolute; z-index: 1; transform: matrix(1, 0, 0, 1, -138, -95);"><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 0px; top: 0px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: -256px; top: 0px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: -256px; top: -256px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 0px; top: -256px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 256px; top: -256px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 256px; top: 0px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: -512px; top: 0px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: -512px; top: -256px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 512px; top: -256px;"></div><div style="width: 256px; height: 256px; overflow: hidden; position: absolute; left: 512px; top: 0px;"></div></div></div><div style="width: 27px; height: 43px; overflow: hidden; position: absolute; left: -14px; top: -43px; z-index: 0;"><img alt="" src="https://maps.gstatic.com/mapfiles/api-3/images/spotlight-poi2.png" draggable="false" style="position: absolute; left: 0px; top: 0px; width: 27px; height: 43px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div></div><div style="position: absolute; left: 0px; top: 0px; z-index: 0;"><div style="position: absolute; z-index: 1; transform: matrix(1, 0, 0, 1, -138, -95);"><div style="position: absolute; left: 0px; top: 0px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24622!3i14163!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140805!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=29966" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: -256px; top: 0px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24621!3i14163!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140805!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=55758" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: -256px; top: -256px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24621!3i14162!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140805!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=43700" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: 0px; top: -256px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24622!3i14162!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140696!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=16102" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: 256px; top: -256px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24623!3i14162!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140696!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=121381" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: 256px; top: 0px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24623!3i14163!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140805!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=4174" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: 512px; top: -256px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24624!3i14162!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140216!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=43265" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: -512px; top: 0px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24620!3i14163!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140805!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=81550" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: -512px; top: -256px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24620!3i14162!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140805!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=69492" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div><div style="position: absolute; left: 512px; top: 0px; width: 256px; height: 256px;"><img draggable="false" alt="" role="presentation" src="https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i15!2i24624!3i14163!4i256!2m3!1e2!6m1!3e5!2m3!1e0!2sm!3i435140805!3m14!2sko-KR!3sUS!5e18!12m1!1e68!12m3!1e37!2m1!1ssmartmaps!12m4!1e26!2m2!1sstyles!2zcC5zOi02MHxwLmw6LTYw!4e0!23i1301875&amp;key=AIzaSyBjxvF9oTfcziZWw--3phPVx1ztAsyhXL4&amp;token=109453" style="width: 256px; height: 256px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div></div></div></div><div class="gm-style-pbc" style="z-index: 2; position: absolute; height: 100%; width: 100%; padding: 0px; border-width: 0px; margin: 0px; left: 0px; top: 0px; opacity: 0;"><p class="gm-style-pbt"></p></div><div style="z-index: 3; position: absolute; height: 100%; width: 100%; padding: 0px; border-width: 0px; margin: 0px; left: 0px; top: 0px; touch-action: pan-x pan-y;"><div style="z-index: 4; position: absolute; left: 50%; top: 50%; width: 100%; transform: translate(0px, 0px);"><div style="position: absolute; left: 0px; top: 0px; z-index: 104; width: 100%;"></div><div style="position: absolute; left: 0px; top: 0px; z-index: 105; width: 100%;"></div><div style="position: absolute; left: 0px; top: 0px; z-index: 106; width: 100%;"><div style="width: 27px; height: 43px; overflow: hidden; position: absolute; opacity: 0; left: -14px; top: -43px; z-index: 0;"><img alt="" src="https://maps.gstatic.com/mapfiles/api-3/images/spotlight-poi2.png" draggable="false" usemap="#gmimap0" style="position: absolute; left: 0px; top: 0px; width: 27px; height: 43px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"><map name="gmimap0" id="gmimap0"><area log="miw" coords="13.5,0,4,3.75,0,13.5,13.5,43,27,13.5,23,3.75" shape="poly" title="Office" style="cursor: pointer; touch-action: none;"></map></div></div><div style="position: absolute; left: 0px; top: 0px; z-index: 107; width: 100%;"></div></div></div></div><iframe aria-hidden="true" frameborder="0" style="z-index: -1; position: absolute; width: 100%; height: 100%; top: 0px; left: 0px; border: none;" src="about:blank"></iframe><div style="margin-left: 5px; margin-right: 5px; z-index: 1000000; position: absolute; left: 0px; bottom: 0px;"><a target="_blank" rel="noopener" href="https://maps.google.com/maps?ll=23.691108,90.51128&amp;z=15&amp;t=m&amp;hl=ko-KR&amp;gl=US&amp;mapclient=apiv3" title="Google 지도에서 이 지역을 보려면 클릭하세요." style="position: static; overflow: visible; float: none; display: inline;"><div style="width: 66px; height: 26px; cursor: pointer;"><img alt="" src="https://maps.gstatic.com/mapfiles/api-3/images/google4.png" draggable="false" style="position: absolute; left: 0px; top: 0px; width: 66px; height: 26px; user-select: none; border: 0px; padding: 0px; margin: 0px;"></div></a></div><div style="background-color: white; padding: 15px 21px; border: 1px solid rgb(171, 171, 171); font-family: Roboto, Arial, sans-serif; color: rgb(34, 34, 34); box-sizing: border-box; box-shadow: rgba(0, 0, 0, 0.2) 0px 4px 16px; z-index: 10000002; display: none; width: 300px; height: 180px; position: absolute; left: 78px; top: 60px;"><div style="padding: 0px 0px 10px; font-size: 16px;">지도 데이터</div><div style="font-size: 13px;">지도 데이터 ©2018 Google</div><div style="width: 13px; height: 13px; overflow: hidden; position: absolute; opacity: 0.7; right: 12px; top: 12px; z-index: 10000; cursor: pointer;"><img alt="" src="https://maps.gstatic.com/mapfiles/api-3/images/mapcnt6.png" draggable="false" style="position: absolute; left: -2px; top: -336px; width: 59px; height: 492px; user-select: none; border: 0px; padding: 0px; margin: 0px; max-width: none;"></div></div><div class="gmnoprint" style="z-index: 1000001; position: absolute; right: 145px; bottom: 0px; width: 131px;"><div draggable="false" class="gm-style-cc" style="user-select: none; height: 14px; line-height: 14px;"><div style="opacity: 0.7; width: 100%; height: 100%; position: absolute;"><div style="width: 1px;"></div><div style="background-color: rgb(245, 245, 245); width: auto; height: 100%; margin-left: 1px;"></div></div><div style="position: relative; padding-right: 6px; padding-left: 6px; font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); white-space: nowrap; direction: ltr; text-align: right; vertical-align: middle; display: inline-block;"><a style="text-decoration: none; cursor: pointer; display: none;">지도 데이터</a><span>지도 데이터 ©2018 Google</span></div></div></div><div class="gmnoscreen" style="position: absolute; right: 0px; bottom: 0px;"><div style="font-family: Roboto, Arial, sans-serif; font-size: 11px; color: rgb(68, 68, 68); direction: ltr; text-align: right; background-color: rgb(245, 245, 245);">지도 데이터 ©2018 Google</div></div><div class="gmnoprint gm-style-cc" draggable="false" style="z-index: 1000001; user-select: none; height: 14px; line-height: 14px; position: absolute; right: 0px; bottom: 0px;"><div style="opacity: 0.7; width: 100%; height: 100%; position: absolute;"><div style="width: 1px;"></div><div style="background-color: rgb(245, 245, 245); width: auto; height: 100%; margin-left: 1px;"></div></div><div style="position: relative; padding-right: 6px; padding-left: 6px; font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); white-space: nowrap; direction: ltr; text-align: right; vertical-align: middle; display: inline-block;"><a href="https://www.google.com/intl/ko-KR_US/help/terms_maps.html" target="_blank" rel="noopener" style="text-decoration: none; cursor: pointer; color: rgb(68, 68, 68);">이용약관</a></div></div><button draggable="false" title="전체 화면보기로 전환" aria-label="전체 화면보기로 전환" type="button" class="gm-control-active gm-fullscreen-control" style="background: none rgb(255, 255, 255); border: 0px; margin: 10px; padding: 0px; position: absolute; cursor: pointer; user-select: none; border-radius: 2px; height: 40px; width: 40px; box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 4px -1px; overflow: hidden; top: 0px; right: 0px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%20018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M0%2C0v2v4h2V2h4V0H2H0z%20M16%2C0h-4v2h4v4h2V2V0H16z%20M16%2C16h-4v2h4h2v-2v-4h-2V16z%20M2%2C12H0v4v2h2h4v-2H2V12z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 11px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M0%2C0v2v4h2V2h4V0H2H0z%20M16%2C0h-4v2h4v4h2V2V0H16z%20M16%2C16h-4v2h4h2v-2v-4h-2V16z%20M2%2C12H0v4v2h2h4v-2H2V12z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 11px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M0%2C0v2v4h2V2h4V0H2H0z%20M16%2C0h-4v2h4v4h2V2V0H16z%20M16%2C16h-4v2h4h2v-2v-4h-2V16z%20M2%2C12H0v4v2h2h4v-2H2V12z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 11px;"></button><div draggable="false" class="gm-style-cc" style="user-select: none; height: 14px; line-height: 14px; display: none; position: absolute; right: 0px; bottom: 0px;"><div style="opacity: 0.7; width: 100%; height: 100%; position: absolute;"><div style="width: 1px;"></div><div style="background-color: rgb(245, 245, 245); width: auto; height: 100%; margin-left: 1px;"></div></div><div style="position: relative; padding-right: 6px; padding-left: 6px; font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); white-space: nowrap; direction: ltr; text-align: right; vertical-align: middle; display: inline-block;"><a target="_blank" rel="noopener" title="Google에 도로 지도 또는 이미지 오류 신고" href="https://www.google.com/maps/@23.6911078,90.5112799,15z/data=!10m1!1e1!12b1?source=apiv3&amp;rapsrc=apiv3" style="font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); text-decoration: none; position: relative;">지도 오류 신고</a></div></div><div class="gmnoprint gm-bundled-control gm-bundled-control-on-bottom" draggable="false" controlwidth="40" controlheight="81" style="margin: 10px; user-select: none; position: absolute; bottom: 107px; left: 0px;"><div class="gmnoprint" controlwidth="40" controlheight="81" style="position: absolute; left: 0px; top: 0px;"><div draggable="false" style="user-select: none; box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 4px -1px; border-radius: 2px; cursor: pointer; background-color: rgb(255, 255, 255); width: 40px; height: 81px;"><button draggable="false" title="확대" aria-label="확대" type="button" class="gm-control-active" style="background: none; display: block; border: 0px; margin: 0px; padding: 0px; position: relative; cursor: pointer; user-select: none; overflow: hidden; width: 40px; height: 40px; top: 0px; left: 0px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23666%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 9px 11px 13px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23333%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 9px 11px 13px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpolygon%20fill%3D%22%23111%22%20points%3D%2218%2C7%2011%2C7%2011%2C0%207%2C0%207%2C7%200%2C7%200%2C11%207%2C11%207%2C18%2011%2C18%2011%2C11%2018%2C11%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 9px 11px 13px;"></button><div style="position: relative; overflow: hidden; width: 30px; height: 1px; margin: 0px 5px; background-color: rgb(230, 230, 230); top: 0px;"></div><button draggable="false" title="축소" aria-label="축소" type="button" class="gm-control-active" style="background: none; display: block; border: 0px; margin: 0px; padding: 0px; position: relative; cursor: pointer; user-select: none; overflow: hidden; width: 40px; height: 40px; top: 0px; left: 0px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 13px 11px 9px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 13px 11px 9px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218%22%20height%3D%2218%22%20viewBox%3D%220%200%2018%2018%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M0%2C7h18v4H0V7z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 18px; width: 18px; margin: 13px 11px 9px;"></button></div></div></div><div class="gmnoprint gm-bundled-control gm-bundled-control-on-bottom" draggable="false" controlwidth="0" controlheight="0" style="margin: 10px; user-select: none; position: absolute; display: none; bottom: 14px; right: 0px;"><div class="gmnoprint" controlwidth="40" controlheight="40" style="display: none; position: absolute;"><div style="width: 40px; height: 40px;"><button draggable="false" title="Rotate map 90 degrees" aria-label="Rotate map 90 degrees" type="button" class="gm-control-active" style="background: none rgb(255, 255, 255); display: none; border: 0px; margin: 0px 0px 32px; padding: 0px; position: relative; cursor: pointer; user-select: none; width: 40px; height: 40px; top: 0px; left: 0px; overflow: hidden; box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 4px -1px; border-radius: 2px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 28px; width: 28px; margin: 6px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 28px; width: 28px; margin: 6px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2224%22%20height%3D%2222%22%20viewBox%3D%220%200%2024%2022%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20fill-rule%3D%22evenodd%22%20d%3D%22M20%2010c0-5.52-4.48-10-10-10s-10%204.48-10%2010v5h5v-5c0-2.76%202.24-5%205-5s5%202.24%205%205v5h-4l6.5%207%206.5-7h-4v-5z%22%20clip-rule%3D%22evenodd%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="height: 28px; width: 28px; margin: 6px;"></button><button draggable="false" title="Tilt map" aria-label="Tilt map" type="button" class="gm-tilt gm-control-active" style="background: none rgb(255, 255, 255); display: block; border: 0px; margin: 0px; padding: 0px; position: relative; cursor: pointer; user-select: none; width: 40px; height: 40px; top: 0px; left: 0px; overflow: hidden; box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 4px -1px; border-radius: 2px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23666%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="width: 18px; height: 16px; margin: 12px 11px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23333%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="width: 18px; height: 16px; margin: 12px 11px;"><img src="data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2218px%22%20height%3D%2216px%22%20viewBox%3D%220%200%2018%2016%22%3E%0A%20%20%3Cpath%20fill%3D%22%23111%22%20d%3D%22M0%2C16h8V9H0V16z%20M10%2C16h8V9h-8V16z%20M0%2C7h8V0H0V7z%20M10%2C0v7h8V0H10z%22%2F%3E%0A%3C%2Fsvg%3E%0A" style="width: 18px; height: 16px; margin: 12px 11px;"></button></div></div></div><div draggable="false" class="gm-style-cc" style="position: absolute; user-select: none; height: 14px; line-height: 14px; right: 52px; bottom: 0px;"><div style="opacity: 0.7; width: 100%; height: 100%; position: absolute;"><div style="width: 1px;"></div><div style="background-color: rgb(245, 245, 245); width: auto; height: 100%; margin-left: 1px;"></div></div><div style="position: relative; padding-right: 6px; padding-left: 6px; font-family: Roboto, Arial, sans-serif; font-size: 10px; color: rgb(68, 68, 68); white-space: nowrap; direction: ltr; text-align: right; vertical-align: middle; display: inline-block;"><span>200 m&nbsp;</span><div style="position: relative; display: inline-block; height: 8px; bottom: -1px; width: 50px;"><div style="width: 100%; height: 4px; position: absolute; left: 0px; top: 0px;"></div><div style="width: 4px; height: 8px; left: 0px; top: 0px; background-color: rgb(255, 255, 255);"></div><div style="width: 4px; height: 8px; position: absolute; background-color: rgb(255, 255, 255); right: 0px; bottom: 0px;"></div><div style="position: absolute; background-color: rgb(102, 102, 102); height: 2px; left: 1px; bottom: 1px; right: 1px;"></div><div style="position: absolute; width: 2px; height: 6px; left: 1px; top: 1px; background-color: rgb(102, 102, 102);"></div><div style="width: 2px; height: 6px; position: absolute; background-color: rgb(102, 102, 102); bottom: 1px; right: 1px;"></div></div></div></div></div></div><div style="background-color: white; font-weight: 500; font-family: Roboto, sans-serif; padding: 15px 25px; box-sizing: border-box; top: 5px; border: 1px solid rgba(0, 0, 0, 0.12); border-radius: 5px; left: 50%; max-width: 375px; position: absolute; transform: translateX(-50%); width: calc(100% - 10px); z-index: 1;"><div><img alt="" src="https://maps.gstatic.com/mapfiles/api-3/images/google_gray.svg" draggable="false" style="padding: 0px; margin: 0px; border: 0px; height: 17px; vertical-align: middle; width: 52px; user-select: none;"></div><div style="line-height: 20px; margin: 15px 0px;"><span style="color: rgba(0, 0, 0, 0.87); font-size: 14px;">Google 지도를 제대로 로드할 수 없습니다.</span></div><table style="width: 100%;"><tr><td style="line-height: 16px; vertical-align: middle;"><a href="https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&amp;utm_medium=degraded&amp;utm_campaign=billing#api-key-and-billing-errors" target="_blank" rel="noopener" style="color: rgba(0, 0, 0, 0.54); font-size: 12px;">Do you own this website?</a></td><td style="text-align: right;"><button class="dismissButton">OK</button></td></tr></table></div></div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<div class="col-md-6">'
                    +'<div class="msg">'
                        +'<div class="msg_title">'
                            +'<h5>Drop A Message</h5>'
                        +'</div>'
                        +'<div class="form_area">'
                            +'<!-- CONTACT FORM -->'
                            +'<div class="contact-form wow fadeIn  animated" data-wow-offset="10" data-wow-duration="1.5s" style="visibility: visible; animation-duration: 1.5s; animation-name: fadeIn;">'
                                +'<div id="message"></div>'
                                +'<form action="scripts/contact.php" class="form-horizontal contact-1" role="form" name="contactform" id="contactform">'
                                    +'<div class="form-group">'
                                        +'<div class="col-sm-6">'
                                            +'<input type="text" class="form-control" name="name" id="name" placeholder="Name">'
                                        +'</div>'
                                        +'<div class="col-sm-6">'
                                            +'<input type="text" class="form-control" name="email" id="email" placeholder="Email">'
                                        +'</div>'
                                    +'</div>'
                                    +'<div class="form-group">'
                                        +'<div class="col-sm-12">'
                                            +'<input type="subject" class="form-control" id="subject" placeholder="Subject *">'
                                            +'<div class="text_area">'
                                                +'<textarea name="contact-message" id="msg" class="form-control" cols="30" rows="8" placeholder="Message"></textarea>'
                                            +'</div>'
                                            +'<button type="submit" class="btn custom-btn" data-loading-text="Loading...">Send</button>'
                                        +'</div>'
                                    +'</div>'
                                +'</form>'
                            +'</div>'
                        +'</div>'
                    +'</div>'
                +'</div>'
                +'<!--End of col-md-6-->'
            +'</div>'
            +'<!--End of row-->'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!--End of contact-->'
+''
+''
+''
    +'<!--Start of footer-->'
    +'<section id="footer">'
        +'<div class="container">'
            +'<div class="row text-center">'
                +'<div class="col-md-6">'
                    +'<div class="copyright">'
                        +'<p>@ 2016 - Design By <span><a href="">♆</a></span></p>'
                    +'</div>'
                +'</div>'
                +'<div class="col-md-6">'
                    +'<div class="designer">'
                        +'<p>A Design By <a href="#">XpeedStudio</a></p>'
                    +'</div>'
                +'</div>'
            +'</div>'
            +'<!--End of row-->'
        +'</div>'
        +'<!--End of container-->'
    +'</section>'
    +'<!--End of footer-->'
+''
+''
+''
    +'<!--Scroll to top-->'
    +'<a href="#" id="back-to-top" title="Back to top" class="show">↑</a>'
    +'<!--End of Scroll to top-->'
+''
+''

+'</div>'
;
}


/*

 */

/*
  
 '<div id="service">'
	+'<div class="container">'
	+'<div class="row centered">'
		+'<div class="col-md-4">'
			+'<i class="fa fa-heart-o"></i>'
			+'<h4>Handsomely Crafted</h4>'
			+'<p>Lorem Ipsum is simply dummy text of the printing and'
				+'dummy text ever since the 1500s, when an unknown printer took a'
				+'galley of type and scrambled it to make a type specimen book.</p>'
			+'<p>'
				+'<br />'
				+'<a href="#" class="btn btn-theme">More Info</a>'
			+'</p>'
		+'</div>'
		+'<div class="col-md-4">'
			+'<i class="fa fa-flask"></i>'
			+'<h4>Retina Ready</h4>'
			+'<p>Lorem Ipsum is simply dummy text of the printing and'
				+'dummy text ever since the 1500s, when an unknown printer took a'
				+'galley of type and scrambled it to make a type specimen book.</p>'
			+'<p>'
				+'<br />'
				+'<a href="#" class="btn btn-theme">More Info</a>'
			+'</p>'
		+'</div>'
		+'<div class="col-md-4">'
			+'<i class="fa fa-trophy"></i>'
			+'<h4>Quality Theme</h4>'
			+'<p>Lorem Ipsum is simply dummy text of the printing and'
				+'dummy text ever since the 1500s, when an unknown printer took a'
				+'galley of type and scrambled it to make a type specimen book.</p>'
			+'<p>'
				+'<br />'
				+'<a href="#" class="btn btn-theme">More Info</a>'
			+'</p>'
		+'</div>'
	+'</div>'
+'</div>'
+'</div>'
  
 */
