function mainUI(){
	return '<div id="headerwrap">'
	+'<div class="container">'
	+'<div class="row">'
		+'<div class="col-lg-8 col-lg-offset-2">'
			+'<h6>MC 달팽 !!! </h6>'
		+'</div>'
		+'<div class="col-lg-8 col-lg-offset-2 himg">'
		+'<iframe width="640" height="360" src="https://www.youtube.com/embed/_je97PWLoBQ?ecver=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>'
			+'<img src="'+$.img()+'/browser.png"'
				+'class="img-responsive">'
		+'</div>'
	+'</div>'
	+'<!-- /row -->'
+'</div>'
+'<!-- /container -->'
+'</div>'
+'<!-- /headerwrap -->';
}

/*'<div id="headerwrap">'
+'<div class="container">'
		+'<div class="row">'
			+'<div class="col-lg-8 col-lg-offset-2">'
				+'<h6>MC 달팽 !!! </h6>'
			+'</div>'
			+'<div class="col-lg-8 col-lg-offset-2 himg">'
			+'<iframe width="640" height="360" src="https://www.youtube.com/embed/_je97PWLoBQ?ecver=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>'
				+'<img src="'+$.img()+'/browser.png"'
					+'class="img-responsive">'
			+'</div>'
		+'</div>'
		+'<!-- /row -->'
	+'</div>'
	+'<!-- /container -->'
+'</div>'
+'<!-- /headerwrap -->';*/



/*+'<div class="header_menu text-center affix-top" data-spy="affix" data-offset-top="50" id="nav">'
+'<div class="container">'
+'<nav class="navbar navbar-default zero_mp ">'
    +'<!-- Brand and toggle get grouped for better mobile display -->'
    +'<div class="navbar-header">'
        +'<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">'
            +'<span class="sr-only">Toggle navigation</span>'
            +'<span class="icon-bar"></span>'
            +'<span class="icon-bar"></span>'
            +'<span class="icon-bar"></span>'
        +'</button>'
        +'<a class="navbar-brand custom_navbar-brand" href="#"><img src="img/logo.png" alt=""></a>'
    +'</div>'
    +'<!--End of navbar-header-->'
    +'<!-- Collect the nav links, forms, and other content for toggling -->'
    +'<div class="collapse navbar-collapse zero_mp" id="bs-example-navbar-collapse-1">'
        +'<ul class="nav navbar-nav navbar-right main_menu">'
            +'<li class="active"><a href="#header">Home <span class="sr-only">(current)</span></a></li>'
            +'<li><a href="#welcome">음악</a></li>'
            +'<li><a href="#portfolio">추천</a></li>'
            +'<li><a href="#counter">내음악</a></li>'
        +'</ul>'
    +'</div>'
    +'<!-- /.navbar-collapse -->'
+'</nav>'
+'<!--End of nav-->'
+'</div>'
+'<!--End of container-->'
+'</div>';*/