function sNavUI() {
	return '<div id="header" style="margin-top:80px">'
			+ '<div class="header_menu text-center affix" data-spy="affix" data-offset-top="50" id="nav">'
			+ '<div class="container-fluid">'
			+ '<nav class="navbar navbar-default zero_mp ">'
			+'<div class="row">'
			  +'<div class="col-md-2">'
			  +'</br>'
			  +'</br>'
			  +'logologologologo'
			  +'</div>'
			  +'<div class="col-md-3">'
			  +'</br>'
			  +'</br>'
			  +'searchsearchsearchsearchsearchsearchsearchsearchsearchsearchsearchsearch'
			  +'</div>'
			  +'<div class="col-md-6">'
			  /* 삼선 */
				+ '<div class="navbar-header">'
				+ '<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapseNav" aria-expanded="false">'
				+ '<span class="sr-only">Toggle navigation</span>'
				+ '<span class="icon-bar"></span>'
				+ '<span class="icon-bar"></span>'
				+ '<span class="icon-bar"></span>'
				+ '</button>'
				+ '<a class="navbar-brand custom_navbar-brand" href="#"></a>'
				+ '</div>'
				/*--삼선--*/
				/* userBox */
				+ '<div class="collapse navbar-collapse collapseNav" id="userBox">'
				+ '<ul class="nav navbar-nav navbar-right main_menu">'
				+ '<li class="loginBtn"><a id ="loginBtn" href="#" class="loginBtn">LOGIN</a></li>'
				+ '<li class="addBtn"><a id ="addBtn" href="#" class="addBtn">회원가입</a></li>'
				+ '</ul>'
				+ '</div>'
				/*--userBox--*/
				/* serviceBox */
				+ '<!-- /.navbar-collapse -->'
				+ '<!-- Collect the nav links, forms, and other content for toggling -->'
				+ '<div class="collapse navbar-collapse collapseNav" id="serviceBox">'
				+ '<ul class="nav navbar-nav navbar-right main_menu">'
				+ '<li class="chartBtn"><a href="#chartBtn" class="chartBtn">차트 <span class="sr-only">(current)</span></a></li>'
				+ '<li class="albumBtn"><a href="#albumBtn" class="albumBtn">최신앨범</a></li>'
				+ '<li class="djBtn"><a href="#djBtn" class="djBtn">뮤직DJ</a></li>'
				+ '<li class="forBtn"><a href="#forBtn" class="forBtn">FOR YOU</a></li>'
				+ '</ul>' 
				+ '</div>' 
				/*--serviceBox--*/
			  +'</div>'
			  +'<div class="col-md-1">'
			  +'</br>'
			  +'</br>'
			  +'여백'
			+'</div>'
			+'</div>'
			+ '<!-- /.navbar-collapse -->' 
			+ '</nav>'
			+ '<!--End of nav-->' 
			+ '</div>' 
			+ '<!--End of container-->'
			+ '</div>' 
			+ '<!--End of header menu-->' 
			+ '</div>'; /* 이거야 */
}
